#!/bin/bash

name=$1 && shift
run_deps="$(scanelf -nBR "$@"|awk '{gsub(",", "\nso:", $2); print "so:" $2}'|sort -u|xargs -r apk info -e|sort -u)"
if [ -n "$run_deps" ]; then
    apk add --no-cache --virtual $name $run_deps
fi

